let button = document.getElementById('btn');
let newQuote = document.getElementById('quote');
let quotes = [
    ' My biggest professional development was getting comfortable admitting what i dont know. - Jessica Rose',
    ' It will be pretty when we get there, but it wont be pretty along the way. - Ed Catmull' , 
    ' I have not failed, I have found 10,000 ways that wont work. - Thomas Edison' , 
    ' Stay hungry , Stay foolish. - Steve Jobs',
    ' The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela',
    ' If life were predictable it would cease to be life, and be without flavour - Eleanor Roosevelt',
    ' If you look at what you have in life, you will always have more. If you look at what you dont have in life, you will never have enough. - Oprah Winfrey' ,
    ' Life is what happens when you are busy making other plans. - Jhon lennon', 
    ' The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt',
    ' It is during our darkest moments that we must focus to see the light.  - Aristotle ',
    ' Whoever is happy will make others happy too. - Anne Frank',
    ' You will face many defeats in life, but never let yourself be defeated. - Maya Angelou', 
    ' Life is either a daring adeventur or nothing at all. - Helen Keller' , 
    ' Live in the sunshine , swim the sea, drink the wild air. - Ralph Waldo' ,
    ' Success is not final. Failure is not fatal. It is the courage to continue that counts. - Winston S. Churchill',
    ' I find that the harder I work, the more luck I seem to have. - Thomas Jefferson',
    ' I never dreamed about success, I worked for it. - Estee Lauder',
    ' There are no sectrets to success. It is the result of preparation, hard work, and learning from failure. - Colin Powell',
    ' It is better to fail in originality than to succeed in imitation. - Herman Melville' ,
    ' I failed my way to success. - Thomas Edison',
    ' If you really look closely, most overnight successes took a long time. - Steve Jobs',
    ' Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill',
    ' Before anything else, preperation is the key to success. - Alexander Graham Bell' , 
    ' You miss 100% of the shots you do not take. - Wayne Gretzky',
    ' Believe you can and you are halfway there. - Theodore Roosevelt',
    ' You become what you believe. - Oprah Winfrey', 
    ' An unexamined life is not worth living. - Socrates',
    ' Dream big and dare to fail. - Norman Vaughan',
    ' Too many of us are not living our dreams because we are living our fears. - Les Brown',
    ' Dreaming, after all, is a form of planning. - Gloria Steinem',
    ' I would rather die of passion than of boredom. - Vincent van Gogh',
    ' Live as if you were to die tomorrow. Learn as if you were to live forever. - Mahatma Gandhi',
    ' Be yourself, everyone is already taken. - Oscar Wilde',
    ' If you cannot do great things, do small things in a great way. - Napoleon Hill',
    ' If opportunity does not knock, build a door. - Milton Berle',
    ' Strive not to be a success, but rather to be of value. - Albert Einstein',
    ' Either you run the day, or the day runs you. - Jim Rohn',
    ' Everything has beauty, but not everyone can see. - Confucius',
    ' Change your thoughts and you change your world. - Norman Vincent',
    ' Remember that happiness is a way of travel, not a destination. - Roy M. Goodman',
    ' It is never too late to be what you might have been. - George Eliot', 
    ' He who angers you conquers you. - Elizabeth Kenny',
    ' A happy family is but an earlier heaven. - George Bernard Shaw',
    ' Always forgive your enemies, nothing annoys them so much. - Oscar Wilde',
    ' The only true wisdom is knowing that you know nothing. - Socrates',
    ' If you do not make mistakes, you are not working on hard enough problems. - Frank Wilczek',
    ' Your worth consists in what you are and not in what you have. - Thomas Edison',
    ' Just be yourself, there is no one better. - Taylor Swift',
    ' I am intimidated by the fear of being average. - Taylor Swift', 
    ' This is a new year. A new beginning. And things will change. - Taylor Swift',
    ' We have a choice. To live or To exist. - Harry Styles',
    ' A dream is only a dream until you decide to make it real. - Harry Styles',
    ' The secret of getting ahead is getting started. Mark Twain',
    ' Only the paranoid survive. - Andy Grove',
    ' Whatever you are, be a good one. - Abraham Licoln',
    ' The hard days are what makes you stronger. - Aly raisman',
    ' Work hard in silence, let your success be the noise. - Frank Ocean',
    ' H.O.P.E. = Hold on. Pain Ends. - Unknown',
    ' Focus on being productive instead of busy. - Tim Ferriss',
    ' I can and I will. Watch me. - Carrie Green',
    ' What is life without a little risk? - J.K Rowling',
    ' Oh yes, the past can hurt. But the way I see it, you can either run from it or learn from it. - The lion King',
    ' You do not have to be perfect to be amazing. - Unknown',
    ' The best way to predict your future is to create it. - Abraham Lincoln',
    ' Successful people are not gifted, they work hard, then succeed on purpose. - G.K Nielson' ,
    ' You must do the kind of things you cannot do. - Eleanor Roosevelt',
    ' I do not fear computers. I fear lack of them. - Isaac Asimov',
    ' It is hardware that makes a machine fast. It is a software that makes a fast machine slow. - Craig Bruce',
    ' The way to get started is to quit talking and start doing. - Walt Disney',
    ' Knowing is not enough, we must apply. Wishing is not enough, we must do. - Johann Wolfgang',
    ' Do what you can with all you have, wherever you are. - Theodore Roosevelt',
    ' You are never too old to set another goal or to dream a new dream. - C.S Lewis'

];

button.addEventListener('click', function(){
    let randomQuote = quotes[Math.floor(Math.random() * quotes.length)];
    quote.innerHTML = randomQuote;
});

